image: chialab/php:7.1

pages:
  stage: deploy
  environment: pages
  before_script:
  - composer install --prefer-dist
  script:
  - ./vendor/bin/generate-site
  cache:
      paths:
      - vendor
  artifacts:
      paths:
      - public
  only:
  - master
