image: nexendrie/php

cache:
  paths:
  - vendor/

pages:
  stage: deploy
  environment:
      name: pages
      url: https://nexendrie.gitlab.io
  script:
  - phing generate
  cache:
      paths:
      - vendor
  artifacts:
      paths:
      - public
  only:
  - master
