image: nexendrie/php

cache:
  paths:
  - vendor/

pages:
  stage: deploy
  environment: pages
  script:
  - phing generate
  cache:
      paths:
      - vendor
  artifacts:
      paths:
      - public
  only:
  - master
